# Generated by Django 4.2.7 on 2024-01-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('primer_apellido', models.CharField(max_length=300)),
                ('segundo_apellido', models.CharField(max_length=300)),
                ('tipo_entrenamiento', models.CharField(default='Normal', max_length=300)),
                ('numero_de_telefono', models.CharField(default='', max_length=300)),
                ('deudor', models.BooleanField(default=False)),
                ('notificado', models.BooleanField(default=False)),
                ('debe_notificarse', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateField()),
                ('ultimo_pago', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='images/')),
                ('horario', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
