# Generated by Django 5.0 on 2024-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11)),
                ('edad', models.IntegerField(blank=True)),
                ('nombre', models.CharField(max_length=300)),
                ('primer_apellido', models.CharField(max_length=300)),
                ('segundo_apellido', models.CharField(max_length=300)),
                ('tipo_entrenamiento', models.CharField(default='Normal', max_length=300)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('ultimo_pago', models.DateField()),
                ('foto', models.ImageField(upload_to='images/<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>')),
            ],
        ),
    ]
