# Generated by Django 5.0 on 2024-01-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_cliente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_pago',
            field=models.DateField(blank=True),
        ),
    ]
