# Generated by Django 5.0 on 2024-01-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_cliente_ultimo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
