# Generated by Django 5.0 on 2024-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_cliente_ultimo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='images/<django.db.models.fields.CharField>/'),
        ),
    ]
