# Generated by Django 4.2.7 on 2024-01-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_de_telefono',
            field=models.CharField(default='', max_length=300),
        ),
    ]
