# Generated by Django 4.2.7 on 2024-01-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_cliente_numero_de_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
