# Generated by Django 4.2.7 on 2024-01-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_cliente_notificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='debe_notificarse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='deudor',
            field=models.BooleanField(default=False),
        ),
    ]
