# Generated by Django 4.2.7 on 2024-01-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_cliente_debe_notificarse_cliente_deudor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
